using System.Collections.Immutable;
using System.Text;
using YTStdSqlBuilder.Generator.TemplateAnalysis;

namespace YTStdSqlBuilder.Generator.Emission
{
    /// <summary>
    /// Generates the C# code for template classes.
    /// </summary>
    internal static class TemplateEmitter
    {
        /// <summary>
        /// Generates the full source code for a template class.
        /// </summary>
        public static string Emit(TemplateClassInfo classInfo)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            if (classInfo.Namespace != null)
            {
                sb.AppendLine($"namespace {classInfo.Namespace}");
                sb.AppendLine("{");
            }

            string indent = classInfo.Namespace != null ? "    " : "";
            string memberIndent = indent + "    ";

            string staticModifier = classInfo.IsStatic ? "static " : "";
            sb.AppendLine($"{indent}public {staticModifier}partial class {classInfo.ClassName}");
            sb.AppendLine($"{indent}{{");

            for (int i = 0; i < classInfo.QueryMethods.Length; i++)
            {
                if (i > 0) sb.AppendLine();
                var query = classInfo.QueryMethods[i];
                EmitQueryMethod(sb, query, classInfo, memberIndent);
            }

            sb.AppendLine($"{indent}}}");

            if (classInfo.Namespace != null)
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static void EmitQueryMethod(
            StringBuilder sb,
            TemplateQueryInfo query,
            TemplateClassInfo classInfo,
            string indent)
        {
            bool isStatic = TemplateSupportAnalyzer.CanGenerateStaticSql(query);
            bool hasResultShape = TemplateSupportAnalyzer.CanGenerateResultShape(query);

            if (isStatic)
            {
                EmitStaticQuery(sb, query, classInfo, indent);
            }
            else
            {
                EmitDynamicQuery(sb, query, classInfo, indent);
            }

            if (hasResultShape)
            {
                sb.AppendLine();
                ResultShapeEmitter.EmitRowClass(sb, query.MethodName, query, indent);
                sb.AppendLine();
                ResultShapeEmitter.EmitReaderMethod(sb, query.MethodName, query, indent);
            }
        }

        private static void EmitStaticQuery(
            StringBuilder sb,
            TemplateQueryInfo query,
            TemplateClassInfo classInfo,
            string indent)
        {
            // Generate SQL constant
            string sql = BuildStaticSql(query);
            sb.AppendLine($"{indent}public const string {query.MethodName}_Sql = \"{EscapeString(sql)}\";");
            sb.AppendLine();

            // Generate method body
            string paramList = BuildParameterList(query.Parameters);
            string staticKeyword = classInfo.IsStatic ? "static " : "";

            sb.AppendLine($"{indent}public {staticKeyword}partial YTStdSqlBuilder.PgSqlRenderResult {query.MethodName}({paramList})");
            sb.AppendLine($"{indent}{{");

            if (query.Parameters.Length == 0)
            {
                sb.AppendLine($"{indent}    return new YTStdSqlBuilder.PgSqlRenderResult(");
                sb.AppendLine($"{indent}        {query.MethodName}_Sql,");
                sb.AppendLine($"{indent}        System.Array.Empty<YTStdSqlBuilder.PgSqlParam>());");
            }
            else
            {
                sb.AppendLine($"{indent}    return new YTStdSqlBuilder.PgSqlRenderResult(");
                sb.AppendLine($"{indent}        {query.MethodName}_Sql,");
                sb.AppendLine($"{indent}        new YTStdSqlBuilder.PgSqlParam[]");
                sb.AppendLine($"{indent}        {{");

                // Map parameters to their ordinal positions in the WHERE clauses
                var paramOrdinals = BuildParamOrdinals(query);
                for (int i = 0; i < paramOrdinals.Count; i++)
                {
                    var (paramName, ordinal) = paramOrdinals[i];
                    string comma = i < paramOrdinals.Count - 1 ? "," : "";
                    sb.AppendLine($"{indent}            new(\"@p{ordinal}\", {paramName}){comma}");
                }

                sb.AppendLine($"{indent}        }});");
            }

            sb.AppendLine($"{indent}}}");
        }

        private static void EmitDynamicQuery(
            StringBuilder sb,
            TemplateQueryInfo query,
            TemplateClassInfo classInfo,
            string indent)
        {
            string paramList = BuildParameterList(query.Parameters);
            string staticKeyword = classInfo.IsStatic ? "static " : "";

            sb.AppendLine($"{indent}public {staticKeyword}partial YTStdSqlBuilder.PgSqlRenderResult {query.MethodName}({paramList})");
            sb.AppendLine($"{indent}{{");

            // Generate runtime builder code
            EmitDynamicBody(sb, query, indent + "    ");

            sb.AppendLine($"{indent}}}");
        }

        private static void EmitDynamicBody(
            StringBuilder sb,
            TemplateQueryInfo query,
            string indent)
        {
            var structure = query.SqlStructure;

            // Emit table definitions
            foreach (var table in query.Tables)
            {
                sb.AppendLine($"{indent}var {table.VariableName} = YTStdSqlBuilder.Table.Def(\"{table.TableName}\").As(\"{table.Alias}\");");
            }

            // Build the query using the runtime builder
            sb.Append($"{indent}var builder = YTStdSqlBuilder.PgSql");

            // SELECT
            sb.AppendLine();
            sb.Append($"{indent}    .Select(");
            for (int i = 0; i < query.SelectColumns.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                var col = query.SelectColumns[i];
                string tableVar = FindTableVar(query.Tables, col.TableAlias);
                if (col.ClrTypeName != "string")
                {
                    sb.Append($"{tableVar}[\"{col.ColumnName}\"].As<{col.ClrTypeName}>()");
                }
                else
                {
                    sb.Append($"{tableVar}[\"{col.ColumnName}\"]");
                }
            }
            sb.AppendLine(")");

            // FROM
            if (structure.FromTable != null)
            {
                sb.AppendLine($"{indent}    .From({structure.FromTable.VariableName})");
            }

            // JOINs
            foreach (var join in structure.Joins)
            {
                string joinMethod = join.JoinType == "LEFT JOIN" ? "LeftJoin" : "Join";
                sb.Append($"{indent}    .{joinMethod}({join.Table.VariableName}, j => j");
                foreach (var onClause in join.OnClauses)
                {
                    string leftVar = FindTableVar(query.Tables, onClause.LeftTableAlias);
                    string rightVar = FindTableVar(query.Tables, onClause.RightTableAlias);
                    string opName = SqlOpToName(onClause.Operator);
                    sb.Append($".On({leftVar}[\"{onClause.LeftColumn}\"], YTStdSqlBuilder.Op.{opName}, {rightVar}[\"{onClause.RightColumn}\"])");
                }
                sb.AppendLine(")");
            }

            // WHERE clauses
            foreach (var where in structure.WhereClauses)
            {
                string leftExpr = $"{FindTableVar(query.Tables, where.LeftTableAlias)}[\"{where.LeftColumn}\"]";
                string opName = SqlOpToName(where.Operator);
                string rightExpr = where.RightParamName != null
                    ? $"YTStdSqlBuilder.Param.Value({where.RightParamName})"
                    : where.RightColumn != null
                        ? $"{FindTableVar(query.Tables, where.RightTableAlias!)}[\"{where.RightColumn}\"]"
                        : "YTStdSqlBuilder.Param.Value(null)";

                string method = where.LogicalOp switch
                {
                    "WHERE" => where.IsConditional ? "WhereIf" : "Where",
                    "AND" => where.IsConditional ? "AndIf" : "And",
                    "OR" => where.IsConditional ? "OrIf" : "Or",
                    _ => "Where"
                };

                if (where.IsConditional && where.ConditionParamName != null)
                {
                    string condition = GenerateConditionExpression(where.ConditionParamName, query.Parameters);
                    sb.AppendLine($"{indent}    .{method}({condition}, {leftExpr}, YTStdSqlBuilder.Op.{opName}, {rightExpr})");
                }
                else
                {
                    sb.AppendLine($"{indent}    .{method}({leftExpr}, YTStdSqlBuilder.Op.{opName}, {rightExpr})");
                }
            }

            // GROUP BY
            if (structure.GroupByColumns.Length > 0)
            {
                sb.Append($"{indent}    .GroupBy(");
                for (int i = 0; i < structure.GroupByColumns.Length; i++)
                {
                    if (i > 0) sb.Append(", ");
                    // GroupBy columns are stored as quoted strings, reconstruct
                    sb.Append($"new YTStdSqlBuilder.Expressions.RawExpr({EscapeStringLiteral(structure.GroupByColumns[i])})");
                }
                sb.AppendLine(")");
            }

            // HAVING
            foreach (var having in structure.HavingClauses)
            {
                string leftExpr = $"{FindTableVar(query.Tables, having.LeftTableAlias)}[\"{having.LeftColumn}\"]";
                string opName = SqlOpToName(having.Operator);
                string rightExpr = having.RightParamName != null
                    ? $"YTStdSqlBuilder.Param.Value({having.RightParamName})"
                    : "YTStdSqlBuilder.Param.Value(null)";
                sb.AppendLine($"{indent}    .Having({leftExpr}, YTStdSqlBuilder.Op.{opName}, {rightExpr})");
            }

            // ORDER BY
            foreach (var orderBy in structure.OrderByColumns)
            {
                string tableVar = FindTableVar(query.Tables, orderBy.TableAlias);
                string method = orderBy.Descending ? "OrderByDesc" : "OrderBy";
                sb.AppendLine($"{indent}    .{method}({tableVar}[\"{orderBy.Column}\"])");
            }

            // LIMIT / OFFSET
            if (structure.Limit.HasValue)
            {
                sb.AppendLine($"{indent}    .Limit({structure.Limit.Value})");
            }
            if (structure.Offset.HasValue)
            {
                sb.AppendLine($"{indent}    .Offset({structure.Offset.Value})");
            }

            // Remove trailing newline for clean chaining
            sb.AppendLine($"{indent}    ;");

            sb.AppendLine($"{indent}return builder.Build();");
        }

        private static string GenerateConditionExpression(string conditionParam, ImmutableArray<TemplateParam> parameters)
        {
            // conditionParam is the base parameter name (e.g., "name") derived from b.Param("name").
            // We append '_condition' to create the boolean parameter name (e.g., "name_condition")
            // that the user declares in their method signature.
            return $"{conditionParam}_condition";
        }

        internal static string BuildStaticSql(TemplateQueryInfo query)
        {
            var sb = new StringBuilder();
            var structure = query.SqlStructure;

            // SELECT
            sb.Append("SELECT ");
            for (int i = 0; i < query.SelectColumns.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                var col = query.SelectColumns[i];
                sb.Append($"\"{col.TableAlias}\".\"{col.ColumnName}\"");

                if (col.Alias != null && col.Alias != col.ColumnName)
                {
                    sb.Append($" AS \"{col.Alias}\"");
                }
            }

            // FROM
            if (structure.FromTable != null)
            {
                sb.Append($" FROM \"{structure.FromTable.TableName}\" AS \"{structure.FromTable.Alias}\"");
            }

            // JOINs
            foreach (var join in structure.Joins)
            {
                sb.Append($" {join.JoinType} \"{join.Table.TableName}\" AS \"{join.Table.Alias}\"");
                if (join.OnClauses.Length > 0)
                {
                    sb.Append(" ON ");
                    for (int i = 0; i < join.OnClauses.Length; i++)
                    {
                        if (i > 0) sb.Append(" AND ");
                        var on = join.OnClauses[i];
                        sb.Append($"\"{on.LeftTableAlias}\".\"{on.LeftColumn}\" {on.Operator} \"{on.RightTableAlias}\".\"{on.RightColumn}\"");
                    }
                }
            }

            // WHERE
            if (structure.WhereClauses.Length > 0)
            {
                var staticClauses = structure.WhereClauses;
                sb.Append(" WHERE ");
                int paramIndex = 0;
                for (int i = 0; i < staticClauses.Length; i++)
                {
                    if (i > 0)
                    {
                        string logicalOp = staticClauses[i].LogicalOp;
                        if (logicalOp == "AND" || logicalOp == "WHERE")
                            sb.Append(" AND ");
                        else if (logicalOp == "OR")
                            sb.Append(" OR ");
                        else
                            sb.Append(" AND ");
                    }

                    var clause = staticClauses[i];
                    sb.Append($"\"{clause.LeftTableAlias}\".\"{clause.LeftColumn}\"");
                    sb.Append($" {clause.Operator} ");

                    if (clause.RightParamName != null)
                    {
                        sb.Append($"@p{paramIndex++}");
                    }
                    else if (clause.RightColumn != null)
                    {
                        sb.Append($"\"{clause.RightTableAlias}\".\"{clause.RightColumn}\"");
                    }
                }
            }

            // GROUP BY
            if (structure.GroupByColumns.Length > 0)
            {
                sb.Append(" GROUP BY ");
                for (int i = 0; i < structure.GroupByColumns.Length; i++)
                {
                    if (i > 0) sb.Append(", ");
                    sb.Append(structure.GroupByColumns[i]);
                }
            }

            // HAVING
            if (structure.HavingClauses.Length > 0)
            {
                sb.Append(" HAVING ");
                int paramIndex = structure.WhereClauses.Length; // Continue param numbering
                for (int i = 0; i < structure.HavingClauses.Length; i++)
                {
                    if (i > 0) sb.Append(" AND ");
                    var clause = structure.HavingClauses[i];
                    sb.Append($"\"{clause.LeftTableAlias}\".\"{clause.LeftColumn}\"");
                    sb.Append($" {clause.Operator} ");
                    if (clause.RightParamName != null)
                    {
                        sb.Append($"@p{paramIndex++}");
                    }
                }
            }

            // ORDER BY
            if (structure.OrderByColumns.Length > 0)
            {
                sb.Append(" ORDER BY ");
                for (int i = 0; i < structure.OrderByColumns.Length; i++)
                {
                    if (i > 0) sb.Append(", ");
                    var orderBy = structure.OrderByColumns[i];
                    sb.Append($"\"{orderBy.TableAlias}\".\"{orderBy.Column}\"");
                    if (orderBy.Descending)
                        sb.Append(" DESC");
                    else
                        sb.Append(" ASC");
                }
            }

            // LIMIT
            if (structure.Limit.HasValue)
            {
                sb.Append($" LIMIT {structure.Limit.Value}");
            }

            // OFFSET
            if (structure.Offset.HasValue)
            {
                sb.Append($" OFFSET {structure.Offset.Value}");
            }

            return sb.ToString();
        }

        private static System.Collections.Generic.List<(string ParamName, int Ordinal)> BuildParamOrdinals(TemplateQueryInfo query)
        {
            var result = new System.Collections.Generic.List<(string, int)>();
            int ordinal = 0;

            // Params appear in WHERE clause order
            foreach (var clause in query.SqlStructure.WhereClauses)
            {
                if (clause.RightParamName != null)
                {
                    result.Add((clause.RightParamName, ordinal++));
                }
            }

            // Then HAVING params
            foreach (var clause in query.SqlStructure.HavingClauses)
            {
                if (clause.RightParamName != null)
                {
                    result.Add((clause.RightParamName, ordinal++));
                }
            }

            return result;
        }

        private static string BuildParameterList(ImmutableArray<TemplateParam> parameters)
        {
            if (parameters.Length == 0) return "";
            var sb = new StringBuilder();
            for (int i = 0; i < parameters.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append($"{parameters[i].TypeName} {parameters[i].ParamName}");
            }
            return sb.ToString();
        }

        private static string FindTableVar(ImmutableArray<TemplateTableRef> tables, string alias)
        {
            foreach (var t in tables)
            {
                if (t.Alias == alias) return t.VariableName;
            }
            return alias;
        }

        private static string SqlOpToName(string sqlOp)
        {
            return sqlOp switch
            {
                "=" => "Eq",
                "!=" => "NotEq",
                ">" => "Gt",
                ">=" => "Gte",
                "<" => "Lt",
                "<=" => "Lte",
                "LIKE" => "Like",
                "ILIKE" => "ILike",
                "NOT LIKE" => "NotLike",
                "NOT ILIKE" => "NotILike",
                "IN" => "In",
                "NOT IN" => "NotIn",
                "IS NULL" => "IsNull",
                "IS NOT NULL" => "IsNotNull",
                "BETWEEN" => "Between",
                "NOT BETWEEN" => "NotBetween",
                "@>" => "ArrayContains",
                "<@" => "ArrayContainedBy",
                "&&" => "ArrayOverlaps",
                _ => "Eq"
            };
        }

        private static string EscapeString(string s)
        {
            return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private static string EscapeStringLiteral(string s)
        {
            return $"\"{s.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";
        }
    }
}
