using System.Collections.Generic;
using System.Text.Json.Serialization;
using YTStdTenantPlatform.Application.Dtos;

namespace YTStdTenantPlatform.Infrastructure.Serialization;

[JsonSourceGenerationOptions(GenerationMode = JsonSourceGenerationMode.Default)]
// ── 基础类型 ──
[JsonSerializable(typeof(ApiResult))]
[JsonSerializable(typeof(ApiResult<long>))]
// ── 认证 ──
[JsonSerializable(typeof(LoginReqDTO))]
[JsonSerializable(typeof(RefreshTokenReqDTO))]
[JsonSerializable(typeof(ApiResult<LoginRepDTO>))]
[JsonSerializable(typeof(ApiResult<CurrentUserRepDTO>))]
// ── 平台用户 ──
[JsonSerializable(typeof(CreatePlatformUserReqDTO))]
[JsonSerializable(typeof(UpdatePlatformUserReqDTO))]
[JsonSerializable(typeof(ApiResult<PlatformUserRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<PlatformUserRepDTO>>))]
// ── 平台角色 ──
[JsonSerializable(typeof(CreatePlatformRoleReqDTO))]
[JsonSerializable(typeof(UpdatePlatformRoleReqDTO))]
[JsonSerializable(typeof(RolePermissionBindReqDTO))]
[JsonSerializable(typeof(RoleMemberBindReqDTO))]
[JsonSerializable(typeof(ApiResult<PlatformRoleRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<PlatformRoleRepDTO>>))]
// ── 平台权限 ──
[JsonSerializable(typeof(ApiResult<PlatformPermissionRepDTO>))]
[JsonSerializable(typeof(ApiResult<List<PlatformPermissionRepDTO>>))]
// ── 租户生命周期 ──
[JsonSerializable(typeof(CreateTenantReqDTO))]
[JsonSerializable(typeof(UpdateTenantReqDTO))]
[JsonSerializable(typeof(TenantStatusChangeReqDTO))]
[JsonSerializable(typeof(ApiResult<TenantRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantRepDTO>>))]
[JsonSerializable(typeof(ApiResult<TenantLifecycleEventRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantLifecycleEventRepDTO>>))]
// ── 租户信息 ──
[JsonSerializable(typeof(CreateTenantGroupReqDTO))]
[JsonSerializable(typeof(CreateTenantDomainReqDTO))]
[JsonSerializable(typeof(CreateTenantTagReqDTO))]
[JsonSerializable(typeof(TagBindReqDTO))]
[JsonSerializable(typeof(ApiResult<TenantGroupRepDTO>))]
[JsonSerializable(typeof(ApiResult<List<TenantGroupRepDTO>>))]
[JsonSerializable(typeof(ApiResult<TenantDomainRepDTO>))]
[JsonSerializable(typeof(ApiResult<List<TenantDomainRepDTO>>))]
[JsonSerializable(typeof(ApiResult<TenantTagRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantTagRepDTO>>))]
// ── 租户资源 ──
[JsonSerializable(typeof(SaveTenantResourceQuotaReqDTO))]
[JsonSerializable(typeof(ApiResult<TenantResourceQuotaRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantResourceQuotaRepDTO>>))]
// ── 租户配置 ──
[JsonSerializable(typeof(UpdateTenantSystemConfigReqDTO))]
[JsonSerializable(typeof(SaveTenantFeatureFlagReqDTO))]
[JsonSerializable(typeof(SaveTenantParameterReqDTO))]
[JsonSerializable(typeof(ApiResult<TenantSystemConfigRepDTO>))]
[JsonSerializable(typeof(ApiResult<TenantFeatureFlagRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantFeatureFlagRepDTO>>))]
[JsonSerializable(typeof(ApiResult<TenantParameterRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantParameterRepDTO>>))]
// ── 套餐 ──
[JsonSerializable(typeof(CreateSaasPackageReqDTO))]
[JsonSerializable(typeof(UpdateSaasPackageReqDTO))]
[JsonSerializable(typeof(CreateSaasPackageVersionReqDTO))]
[JsonSerializable(typeof(SaveSaasPackageCapabilityReqDTO))]
[JsonSerializable(typeof(ApiResult<SaasPackageRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<SaasPackageRepDTO>>))]
[JsonSerializable(typeof(ApiResult<SaasPackageVersionRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<SaasPackageVersionRepDTO>>))]
[JsonSerializable(typeof(ApiResult<SaasPackageCapabilityRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<SaasPackageCapabilityRepDTO>>))]
// ── 订阅 ──
[JsonSerializable(typeof(CreateSubscriptionReqDTO))]
[JsonSerializable(typeof(CreateTrialReqDTO))]
[JsonSerializable(typeof(ApiResult<TenantSubscriptionRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantSubscriptionRepDTO>>))]
[JsonSerializable(typeof(ApiResult<TenantTrialRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantTrialRepDTO>>))]
[JsonSerializable(typeof(ApiResult<TenantSubscriptionChangeRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantSubscriptionChangeRepDTO>>))]
// ── 计费 ──
[JsonSerializable(typeof(CreateBillingInvoiceReqDTO))]
[JsonSerializable(typeof(CreatePaymentOrderReqDTO))]
[JsonSerializable(typeof(CreateRefundReqDTO))]
[JsonSerializable(typeof(ApiResult<BillingInvoiceRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<BillingInvoiceRepDTO>>))]
[JsonSerializable(typeof(ApiResult<BillingInvoiceItemRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<BillingInvoiceItemRepDTO>>))]
[JsonSerializable(typeof(ApiResult<PaymentOrderRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<PaymentOrderRepDTO>>))]
[JsonSerializable(typeof(ApiResult<PaymentRefundRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<PaymentRefundRepDTO>>))]
// ── API集成 ──
[JsonSerializable(typeof(CreateApiKeyReqDTO))]
[JsonSerializable(typeof(CreateWebhookReqDTO))]
[JsonSerializable(typeof(UpdateWebhookReqDTO))]
[JsonSerializable(typeof(ApiResult<TenantApiKeyRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantApiKeyRepDTO>>))]
[JsonSerializable(typeof(ApiResult<ApiKeyCreatedRepDTO>))]
[JsonSerializable(typeof(ApiResult<TenantApiUsageStatRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantApiUsageStatRepDTO>>))]
[JsonSerializable(typeof(ApiResult<WebhookEventRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<WebhookEventRepDTO>>))]
[JsonSerializable(typeof(ApiResult<TenantWebhookRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantWebhookRepDTO>>))]
[JsonSerializable(typeof(ApiResult<WebhookDeliveryLogRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<WebhookDeliveryLogRepDTO>>))]
// ── 平台运营 ──
[JsonSerializable(typeof(ApiResult<TenantDailyStatRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantDailyStatRepDTO>>))]
[JsonSerializable(typeof(ApiResult<PlatformMonitorMetricRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<PlatformMonitorMetricRepDTO>>))]
// ── 审计 ──
[JsonSerializable(typeof(ApiResult<OperationLogRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<OperationLogRepDTO>>))]
[JsonSerializable(typeof(ApiResult<AuditLogRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<AuditLogRepDTO>>))]
[JsonSerializable(typeof(ApiResult<SystemLogRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<SystemLogRepDTO>>))]
// ── 通知 ──
[JsonSerializable(typeof(CreateNotificationTemplateReqDTO))]
[JsonSerializable(typeof(UpdateNotificationTemplateReqDTO))]
[JsonSerializable(typeof(CreateNotificationReqDTO))]
[JsonSerializable(typeof(ApiResult<NotificationTemplateRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<NotificationTemplateRepDTO>>))]
[JsonSerializable(typeof(ApiResult<NotificationRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<NotificationRepDTO>>))]
// ── 存储 ──
[JsonSerializable(typeof(CreateStorageStrategyReqDTO))]
[JsonSerializable(typeof(UpdateStorageStrategyReqDTO))]
[JsonSerializable(typeof(SaveFileAccessPolicyReqDTO))]
[JsonSerializable(typeof(ApiResult<StorageStrategyRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<StorageStrategyRepDTO>>))]
[JsonSerializable(typeof(ApiResult<TenantFileRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantFileRepDTO>>))]
[JsonSerializable(typeof(ApiResult<FileAccessPolicyRepDTO>))]
[JsonSerializable(typeof(ApiResult<PagedResult<FileAccessPolicyRepDTO>>))]
internal partial class TenantPlatformJsonSerializerContext : JsonSerializerContext
{
}
