using System.Collections.Generic;
using System.Linq;
using System.Text;
using YTStdEntity.Generator.Models;

namespace YTStdEntity.Generator.Emitters;

/// <summary>审计查询代码生成器：生成审计查询/历史/比较/主从联合审计查询代码</summary>
internal static class AuditCrudEmitter
{
    /// <summary>生成 {Entity}AuditCRUD.g.cs 内容</summary>
    public static string Emit(EntityModel model)
    {
        var auditTableName = model.TableName + "_audit";
        var cn = model.ClassName;

        var sb = new StringBuilder(8192);
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Npgsql;");
        sb.AppendLine("using NpgsqlTypes;");
        sb.AppendLine("using YTStdAdo;");
        sb.AppendLine("using YTStdEntity.Audit;");
        sb.AppendLine("using YTStdLogger.Core;");
        sb.AppendLine("using YTStdSqlBuilder;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>{cn} 审计查询类（编译期生成）</summary>");
        sb.AppendLine($"    public static partial class {cn}AuditCRUD");
        sb.AppendLine("    {");

        // AuditTableName const
        sb.AppendLine($"        /// <summary>审计表名</summary>");
        sb.AppendLine($"        public const string AuditTableName = \"{auditTableName}\";");
        sb.AppendLine();

        // GetAuditListAsync
        EmitGetAuditListAsync(sb, model);
        sb.AppendLine();

        // GetAuditByIdAsync
        EmitGetAuditByIdAsync(sb, model);
        sb.AppendLine();

        // GetAuditHistoryAsync
        EmitGetAuditHistoryAsync(sb, model);
        sb.AppendLine();

        // DiffAuditSnapshots
        EmitDiffAuditSnapshots(sb, model);

        // Master-detail joint audit query (generated only if this entity has detail tables)
        if (model.DetailTables.Count > 0)
        {
            sb.AppendLine();
            EmitMasterDetailResult(sb, model);
            sb.AppendLine();
            EmitGetMasterDetailAuditAsync(sb, model);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitGetAuditListAsync(StringBuilder sb, EntityModel model)
    {
        var cn = model.ClassName;
        var auditTable = model.TableName + "_audit";

        sb.AppendLine($"        /// <summary>查询 {cn} 审计记录列表（分页）</summary>");
        sb.AppendLine($"        public static async ValueTask<(List<AuditRecord> Records, int TotalCount)> GetAuditListAsync(");
        sb.AppendLine($"            int tenantId, long userId, AuditQueryFilter filter)");
        sb.AppendLine("        {");
        sb.AppendLine($"            Logger.Debug(tenantId, userId, () =>");
        sb.AppendLine($"                $\"[{cn}AuditCRUD.GetAuditListAsync] 进入方法, filter.Id={{filter.Id}}\");");
        sb.AppendLine();

        // Dynamic WHERE building
        sb.AppendLine("            var paramList = new List<PgSqlParam>(8);");
        sb.AppendLine("            var where = \"WHERE 1=1\";");
        sb.AppendLine();

        if (model.IsTenantTable)
        {
            sb.AppendLine("            where += \" AND \\\"tenant_id\\\" = @tenantId\";");
            sb.AppendLine("            paramList.Add(new PgSqlParam(\"@tenantId\", tenantId, NpgsqlDbType.Integer));");
            sb.AppendLine();
        }

        sb.AppendLine("            if (filter.Id.HasValue)");
        sb.AppendLine("            {");
        sb.AppendLine("                where += \" AND \\\"id\\\" = @id\";");
        sb.AppendLine("                paramList.Add(new PgSqlParam(\"@id\", filter.Id.Value, NpgsqlDbType.Bigint));");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            if (filter.Opt.HasValue)");
        sb.AppendLine("            {");
        sb.AppendLine("                where += \" AND \\\"opt\\\" = @opt\";");
        sb.AppendLine("                paramList.Add(new PgSqlParam(\"@opt\", ((char)filter.Opt.Value).ToString(), NpgsqlDbType.Char));");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            if (filter.OperatorId.HasValue)");
        sb.AppendLine("            {");
        sb.AppendLine("                where += \" AND \\\"operator_id\\\" = @operatorId\";");
        sb.AppendLine("                paramList.Add(new PgSqlParam(\"@operatorId\", filter.OperatorId.Value, NpgsqlDbType.Bigint));");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            if (filter.StartTime.HasValue)");
        sb.AppendLine("            {");
        sb.AppendLine("                where += \" AND \\\"operated_at\\\" >= @startTime\";");
        sb.AppendLine("                paramList.Add(new PgSqlParam(\"@startTime\", filter.StartTime.Value, NpgsqlDbType.TimestampTz));");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            if (filter.EndTime.HasValue)");
        sb.AppendLine("            {");
        sb.AppendLine("                where += \" AND \\\"operated_at\\\" <= @endTime\";");
        sb.AppendLine("                paramList.Add(new PgSqlParam(\"@endTime\", filter.EndTime.Value, NpgsqlDbType.TimestampTz));");
        sb.AppendLine("            }");
        sb.AppendLine();

        // Count query
        sb.AppendLine($"            var countSql = $\"SELECT COUNT(*) FROM \\\"{auditTable}\\\" {{where}}\";");
        sb.AppendLine("            var countResult = await DB.GetScalarAsync<long>(countSql, paramList.ToArray(), tenantId, userId);");
        sb.AppendLine("            var totalCount = (int)(countResult.Value);");
        sb.AppendLine();

        // Data query
        sb.AppendLine("            var pageSize = Math.Min(Math.Max(filter.PageSize, 1), 500);");
        sb.AppendLine("            var offset = filter.PageIndex * pageSize;");
        sb.AppendLine();
        sb.AppendLine($"            var dataSql = $\"SELECT \\\"audit_id\\\", \\\"id\\\", \\\"opt\\\", \\\"operated_at\\\", \" +");
        sb.AppendLine($"                $\"\\\"operator_id\\\", \" +");
        if (model.IsTenantTable)
            sb.AppendLine($"                $\"\\\"tenant_id\\\", \" +");
        sb.AppendLine($"                $\"\\\"snapshot\\\" \" +");
        sb.AppendLine($"                $\"FROM \\\"{auditTable}\\\" {{where}} \" +");
        sb.AppendLine($"                $\"ORDER BY \\\"operated_at\\\" DESC, \\\"audit_id\\\" DESC \" +");
        sb.AppendLine($"                $\"LIMIT {{pageSize}} OFFSET {{offset}}\";");
        sb.AppendLine();

        sb.AppendLine("            var (result, records) = await DB.GetListAsync(dataSql, paramList.ToArray(), reader => new AuditRecord");
        sb.AppendLine("            {");
        sb.AppendLine("                AuditId = reader.GetInt64(0),");
        sb.AppendLine("                Id = reader.GetInt64(1),");
        sb.AppendLine("                Opt = (AuditOpt)reader.GetChar(2),");
        sb.AppendLine("                OperatedAt = reader.GetDateTime(3),");
        sb.AppendLine("                OperatorId = reader.GetInt64(4),");
        if (model.IsTenantTable)
        {
            sb.AppendLine("                TenantId = reader.IsDBNull(5) ? null : reader.GetInt32(5),");
            sb.AppendLine("                Snapshot = reader.GetString(6),");
        }
        else
        {
            sb.AppendLine("                Snapshot = reader.GetString(5),");
        }
        sb.AppendLine("            }, tenantId, userId);");
        sb.AppendLine();
        sb.AppendLine($"            Logger.Debug(tenantId, userId, () =>");
        sb.AppendLine($"                $\"[{cn}AuditCRUD.GetAuditListAsync] 完成, totalCount={{totalCount}}, pageRecords={{records?.Count ?? 0}}\");");
        sb.AppendLine();
        sb.AppendLine("            return (records ?? new List<AuditRecord>(), totalCount);");
        sb.AppendLine("        }");
    }

    private static void EmitGetAuditByIdAsync(StringBuilder sb, EntityModel model)
    {
        var cn = model.ClassName;
        var auditTable = model.TableName + "_audit";
        var tenantCol = model.IsTenantTable ? " AND \\\"tenant_id\\\" = @tenantId" : "";

        sb.AppendLine($"        /// <summary>按审计ID获取单条审计记录</summary>");
        sb.AppendLine($"        public static async ValueTask<AuditRecord?> GetAuditByIdAsync(");
        sb.AppendLine($"            int tenantId, long userId, long auditId)");
        sb.AppendLine("        {");
        sb.AppendLine($"            Logger.Debug(tenantId, userId, () =>");
        sb.AppendLine($"                $\"[{cn}AuditCRUD.GetAuditByIdAsync] 进入方法, auditId={{auditId}}\");");
        sb.AppendLine();
        sb.AppendLine("            const string sql =");
        sb.AppendLine($"                \"SELECT \\\"audit_id\\\", \\\"id\\\", \\\"opt\\\", \\\"operated_at\\\", \" +");
        sb.AppendLine($"                \"\\\"operator_id\\\", \" +");
        if (model.IsTenantTable)
            sb.AppendLine($"                \"\\\"tenant_id\\\", \" +");
        sb.AppendLine($"                \"\\\"snapshot\\\" \" +");
        sb.AppendLine($"                \"FROM \\\"{auditTable}\\\" \" +");
        sb.AppendLine($"                \"WHERE \\\"audit_id\\\" = @auditId{tenantCol}\";");
        sb.AppendLine();

        if (model.IsTenantTable)
        {
            sb.AppendLine("            var parameters = new PgSqlParam[]");
            sb.AppendLine("            {");
            sb.AppendLine("                new PgSqlParam(\"@auditId\", auditId, NpgsqlDbType.Bigint),");
            sb.AppendLine("                new PgSqlParam(\"@tenantId\", tenantId, NpgsqlDbType.Integer),");
            sb.AppendLine("            };");
        }
        else
        {
            sb.AppendLine("            var parameters = new PgSqlParam[]");
            sb.AppendLine("            {");
            sb.AppendLine("                new PgSqlParam(\"@auditId\", auditId, NpgsqlDbType.Bigint),");
            sb.AppendLine("            };");
        }
        sb.AppendLine();

        sb.AppendLine("            var (result, data) = await DB.GetListAsync(sql, parameters, reader => new AuditRecord");
        sb.AppendLine("            {");
        sb.AppendLine("                AuditId = reader.GetInt64(0),");
        sb.AppendLine("                Id = reader.GetInt64(1),");
        sb.AppendLine("                Opt = (AuditOpt)reader.GetChar(2),");
        sb.AppendLine("                OperatedAt = reader.GetDateTime(3),");
        sb.AppendLine("                OperatorId = reader.GetInt64(4),");
        if (model.IsTenantTable)
        {
            sb.AppendLine("                TenantId = reader.IsDBNull(5) ? null : reader.GetInt32(5),");
            sb.AppendLine("                Snapshot = reader.GetString(6),");
        }
        else
        {
            sb.AppendLine("                Snapshot = reader.GetString(5),");
        }
        sb.AppendLine("            }, tenantId, userId);");
        sb.AppendLine();
        sb.AppendLine("            var record = (data != null && data.Count > 0) ? data[0] : null;");
        sb.AppendLine($"            Logger.Debug(tenantId, userId, () =>");
        sb.AppendLine($"                $\"[{cn}AuditCRUD.GetAuditByIdAsync] 完成, found={{record != null}}\");");
        sb.AppendLine("            return record;");
        sb.AppendLine("        }");
    }

    private static void EmitGetAuditHistoryAsync(StringBuilder sb, EntityModel model)
    {
        var cn = model.ClassName;
        var auditTable = model.TableName + "_audit";
        var tenantCol = model.IsTenantTable ? " AND \\\"tenant_id\\\" = @tenantId" : "";

        sb.AppendLine($"        /// <summary>获取 {cn} 指定主键的完整审计历史</summary>");
        sb.AppendLine($"        public static async ValueTask<List<AuditRecord>> GetAuditHistoryAsync(");
        sb.AppendLine($"            int tenantId, long userId, long entityId)");
        sb.AppendLine("        {");
        sb.AppendLine($"            Logger.Debug(tenantId, userId, () =>");
        sb.AppendLine($"                $\"[{cn}AuditCRUD.GetAuditHistoryAsync] 进入方法, entityId={{entityId}}\");");
        sb.AppendLine();
        sb.AppendLine("            const string sql =");
        sb.AppendLine($"                \"SELECT \\\"audit_id\\\", \\\"id\\\", \\\"opt\\\", \\\"operated_at\\\", \" +");
        sb.AppendLine($"                \"\\\"operator_id\\\", \" +");
        if (model.IsTenantTable)
            sb.AppendLine($"                \"\\\"tenant_id\\\", \" +");
        sb.AppendLine($"                \"\\\"snapshot\\\" \" +");
        sb.AppendLine($"                \"FROM \\\"{auditTable}\\\" \" +");
        sb.AppendLine($"                \"WHERE \\\"id\\\" = @id{tenantCol} \" +");
        sb.AppendLine($"                \"ORDER BY \\\"operated_at\\\" ASC, \\\"audit_id\\\" ASC\";");
        sb.AppendLine();

        if (model.IsTenantTable)
        {
            sb.AppendLine("            var parameters = new PgSqlParam[]");
            sb.AppendLine("            {");
            sb.AppendLine("                new PgSqlParam(\"@id\", entityId, NpgsqlDbType.Bigint),");
            sb.AppendLine("                new PgSqlParam(\"@tenantId\", tenantId, NpgsqlDbType.Integer),");
            sb.AppendLine("            };");
        }
        else
        {
            sb.AppendLine("            var parameters = new PgSqlParam[]");
            sb.AppendLine("            {");
            sb.AppendLine("                new PgSqlParam(\"@id\", entityId, NpgsqlDbType.Bigint),");
            sb.AppendLine("            };");
        }
        sb.AppendLine();

        sb.AppendLine("            var (result, records) = await DB.GetListAsync(sql, parameters, reader => new AuditRecord");
        sb.AppendLine("            {");
        sb.AppendLine("                AuditId = reader.GetInt64(0),");
        sb.AppendLine("                Id = reader.GetInt64(1),");
        sb.AppendLine("                Opt = (AuditOpt)reader.GetChar(2),");
        sb.AppendLine("                OperatedAt = reader.GetDateTime(3),");
        sb.AppendLine("                OperatorId = reader.GetInt64(4),");
        if (model.IsTenantTable)
        {
            sb.AppendLine("                TenantId = reader.IsDBNull(5) ? null : reader.GetInt32(5),");
            sb.AppendLine("                Snapshot = reader.GetString(6),");
        }
        else
        {
            sb.AppendLine("                Snapshot = reader.GetString(5),");
        }
        sb.AppendLine("            }, tenantId, userId);");
        sb.AppendLine();
        sb.AppendLine($"            Logger.Debug(tenantId, userId, () =>");
        sb.AppendLine($"                $\"[{cn}AuditCRUD.GetAuditHistoryAsync] 完成, count={{records?.Count ?? 0}}\");");
        sb.AppendLine();
        sb.AppendLine("            return records ?? new List<AuditRecord>();");
        sb.AppendLine("        }");
    }

    private static void EmitDiffAuditSnapshots(StringBuilder sb, EntityModel model)
    {
        var cn = model.ClassName;

        sb.AppendLine($"        /// <summary>比较两条审计快照的字段差异</summary>");
        sb.AppendLine("        public static List<AuditDiffField> DiffAuditSnapshots(");
        sb.AppendLine("            int tenantId, long userId, string oldSnapshot, string newSnapshot)");
        sb.AppendLine("        {");
        sb.AppendLine($"            Logger.Debug(tenantId, userId, () => \"[{cn}AuditCRUD.DiffAuditSnapshots] 进入方法\");");
        sb.AppendLine();
        sb.AppendLine("            var diffs = new List<AuditDiffField>();");
        sb.AppendLine("            using var oldDoc = JsonDocument.Parse(oldSnapshot);");
        sb.AppendLine("            using var newDoc = JsonDocument.Parse(newSnapshot);");
        sb.AppendLine("            var oldRoot = oldDoc.RootElement;");
        sb.AppendLine("            var newRoot = newDoc.RootElement;");
        sb.AppendLine();

        foreach (var col in model.Columns)
        {
            sb.AppendLine($"            {{");
            sb.AppendLine($"                string? oldVal = null;");
            sb.AppendLine($"                string? newVal = null;");
            sb.AppendLine($"                if (oldRoot.TryGetProperty(\"{col.ColumnName}\", out var oldProp) && oldProp.ValueKind != JsonValueKind.Null)");
            sb.AppendLine($"                    oldVal = oldProp.ToString();");
            sb.AppendLine($"                if (newRoot.TryGetProperty(\"{col.ColumnName}\", out var newProp) && newProp.ValueKind != JsonValueKind.Null)");
            sb.AppendLine($"                    newVal = newProp.ToString();");
            sb.AppendLine($"                if (!string.Equals(oldVal, newVal, StringComparison.Ordinal))");
            sb.AppendLine($"                {{");
            sb.AppendLine($"                    diffs.Add(new AuditDiffField");
            sb.AppendLine($"                    {{");
            sb.AppendLine($"                        FieldName = \"{col.ColumnName}\",");
            sb.AppendLine($"                        OldValue = oldVal,");
            sb.AppendLine($"                        NewValue = newVal,");
            sb.AppendLine($"                    }});");
            sb.AppendLine($"                }}");
            sb.AppendLine($"            }}");
        }

        sb.AppendLine();
        sb.AppendLine($"            Logger.Debug(tenantId, userId, () =>");
        sb.AppendLine($"                $\"[{cn}AuditCRUD.DiffAuditSnapshots] 差异字段数={{diffs.Count}}\");");
        sb.AppendLine();
        sb.AppendLine("            return diffs;");
        sb.AppendLine("        }");
    }

    private static void EmitMasterDetailResult(StringBuilder sb, EntityModel model)
    {
        var cn = model.ClassName;
        sb.AppendLine($"    /// <summary>{cn} 主从表审计查询结果</summary>");
        sb.AppendLine($"    public sealed class {cn}MasterDetailAuditResult : YTStdEntity.Audit.MasterDetailAuditResult");
        sb.AppendLine("    {");
        foreach (var detail in model.DetailTables)
        {
            sb.AppendLine($"        /// <summary>{detail.DetailClassName} 从表审计记录</summary>");
            sb.AppendLine($"        public List<AuditRecord> {detail.DetailClassName}Records {{ get; init; }} = new();");
        }
        sb.AppendLine("    }");
    }

    private static void EmitGetMasterDetailAuditAsync(StringBuilder sb, EntityModel model)
    {
        var cn = model.ClassName;
        var pk = model.PrimaryKey;
        var pkType = pk != null ? "long" : "long";

        sb.AppendLine($"        /// <summary>查询 {cn} 主从表联合审计记录</summary>");
        sb.AppendLine($"        public static async ValueTask<{cn}MasterDetailAuditResult> GetMasterDetailAuditAsync(");
        sb.AppendLine($"            int tenantId, long userId, {pkType} masterId, AuditQueryFilter? filter = null)");
        sb.AppendLine("        {");
        sb.AppendLine($"            Logger.Debug(tenantId, userId, () =>");
        sb.AppendLine($"                $\"[{cn}AuditCRUD.GetMasterDetailAuditAsync] 进入方法, masterId={{masterId}}\");");
        sb.AppendLine();

        // Query master records
        sb.AppendLine("            var masterFilter = filter ?? new AuditQueryFilter();");
        sb.AppendLine("            masterFilter.Id = masterId;");
        sb.AppendLine($"            var (masterRecords, masterTotal) = await {cn}AuditCRUD.GetAuditListAsync(tenantId, userId, masterFilter);");
        sb.AppendLine();

        // Query each detail table into local variables
        for (int idx = 0; idx < model.DetailTables.Count; idx++)
        {
            var detail = model.DetailTables[idx];
            var detailAuditTable = detail.DetailTableName + "_audit";
            var fkCol = detail.ForeignKeyColumnName;
            var varName = $"detail{idx}Records";

            sb.AppendLine($"            // === 从表: {detail.DetailClassName} ===");
            sb.AppendLine($"            List<AuditRecord> {varName};");
            sb.AppendLine("            {");
            sb.AppendLine($"                var detailParams = new List<PgSqlParam>(6);");

            sb.AppendLine($"                var detailSql = \"SELECT \\\"audit_id\\\", \\\"id\\\", \\\"opt\\\", \\\"operated_at\\\", \" +");
            sb.AppendLine($"                    \"\\\"operator_id\\\", \" +");
            if (model.IsTenantTable)
                sb.AppendLine($"                    \"\\\"tenant_id\\\", \" +");
            sb.AppendLine($"                    \"\\\"snapshot\\\" \" +");
            sb.AppendLine($"                    \"FROM \\\"{detailAuditTable}\\\" \" +");

            if (model.IsTenantTable)
            {
                sb.AppendLine($"                    \"WHERE \\\"tenant_id\\\" = @tenantId \" +");
                sb.AppendLine($"                    \"AND (snapshot->>'{fkCol}')::bigint = @fkId\";");
                sb.AppendLine($"                detailParams.Add(new PgSqlParam(\"@tenantId\", tenantId, NpgsqlDbType.Integer));");
            }
            else
            {
                sb.AppendLine($"                    \"WHERE (snapshot->>'{fkCol}')::bigint = @fkId\";");
            }

            sb.AppendLine($"                detailParams.Add(new PgSqlParam(\"@fkId\", masterId, NpgsqlDbType.Bigint));");
            sb.AppendLine();

            sb.AppendLine("                var (detailResult, detailRecords) = await DB.GetListAsync(");
            sb.AppendLine("                    detailSql, detailParams.ToArray(), reader => new AuditRecord");
            sb.AppendLine("                {");
            sb.AppendLine("                    AuditId = reader.GetInt64(0),");
            sb.AppendLine("                    Id = reader.GetInt64(1),");
            sb.AppendLine("                    Opt = (AuditOpt)reader.GetChar(2),");
            sb.AppendLine("                    OperatedAt = reader.GetDateTime(3),");
            sb.AppendLine("                    OperatorId = reader.GetInt64(4),");
            if (model.IsTenantTable)
            {
                sb.AppendLine("                    TenantId = reader.IsDBNull(5) ? null : reader.GetInt32(5),");
                sb.AppendLine("                    Snapshot = reader.GetString(6),");
            }
            else
            {
                sb.AppendLine("                    Snapshot = reader.GetString(5),");
            }
            sb.AppendLine("                }, tenantId, userId);");
            sb.AppendLine();
            sb.AppendLine($"                {varName} = detailRecords ?? new List<AuditRecord>();");
            sb.AppendLine("            }");
            sb.AppendLine();
        }

        // Construct result using object initializer
        sb.AppendLine($"            var result = new {cn}MasterDetailAuditResult");
        sb.AppendLine("            {");
        sb.AppendLine("                MasterRecords = masterRecords,");
        sb.AppendLine("                TotalCount = masterTotal,");
        for (int idx = 0; idx < model.DetailTables.Count; idx++)
        {
            var detail = model.DetailTables[idx];
            var varName = $"detail{idx}Records";
            var comma = idx < model.DetailTables.Count - 1 ? "," : "";
            sb.AppendLine($"                {detail.DetailClassName}Records = {varName}{comma}");
        }
        sb.AppendLine("            };");
        sb.AppendLine();

        sb.AppendLine($"            Logger.Debug(tenantId, userId, () =>");
        sb.AppendLine($"                $\"[{cn}AuditCRUD.GetMasterDetailAuditAsync] 完成, 主表={{result.MasterRecords.Count}}\");");
        sb.AppendLine();
        sb.AppendLine("            return result;");
        sb.AppendLine("        }");
    }
}
