using System.Collections.Generic;
using System.Linq;
using System.Text;
using YTStdEntity.Generator.Models;

namespace YTStdEntity.Generator.Emitters;

/// <summary>DAL 代码生成器：生成建表/视图/索引/审计表/触发器，调用 DB 方法执行</summary>
internal static class DalEmitter
{
    /// <summary>生成 {Entity}DAL.g.cs 内容</summary>
    public static string Emit(EntityModel model)
    {
        var sb = new StringBuilder(8192);
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Npgsql;");
        sb.AppendLine("using NpgsqlTypes;");
        sb.AppendLine("using YTStdAdo;");
        sb.AppendLine("using YTStdLogger.Core;");
        sb.AppendLine("using YTStdSqlBuilder;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>{model.ClassName} 数据库维护类（编译期生成）</summary>");
        sb.AppendLine($"    public static partial class {model.ClassName}DAL");
        sb.AppendLine("    {");

        EmitCreateTableIfNotExists(sb, model);
        sb.AppendLine();
        EmitEnsureColumnLength(sb, model);
        sb.AppendLine();
        EmitCreateIndexIfNotExists(sb, model);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitCreateTableIfNotExists(StringBuilder sb, EntityModel model)
    {
        var tableName = model.TableName;
        var auditTableName = tableName + "_audit";
        var className = model.ClassName;

        sb.AppendLine($"        /// <summary>创建 {className} 表及相关对象（审计表、触发器等）</summary>");
        sb.AppendLine("        public static async ValueTask<bool> CreateTableIfNotExists(int tenantId, long userId, bool createLogTable)");
        sb.AppendLine("        {");
        sb.AppendLine($"            Logger.Info(tenantId, userId, \"[{className}DAL.CreateTableIfNotExists] 开始创建, 表名={tableName}\");");
        sb.AppendLine();

        // Check if table exists
        sb.AppendLine($"            var existsResult = await DB.GetTableInfor(\"{Esc(tableName)}\");");
        sb.AppendLine("            if (existsResult.Success && existsResult.RowsAffected > 0)");
        sb.AppendLine("            {");
        sb.AppendLine($"                Logger.Info(tenantId, userId, \"[{className}DAL.CreateTableIfNotExists] 表已存在, 跳过: {tableName}\");");
        sb.AppendLine("                return false;");
        sb.AppendLine("            }");
        sb.AppendLine();

        // Build CREATE TABLE SQL
        sb.AppendLine("            // === 主表 ===");
        EmitCreateTableSqlString(sb, model);
        sb.AppendLine();
        sb.AppendLine($"            Logger.Info(tenantId, userId, $\"[{className}DAL.CreateTableIfNotExists] 建表SQL: {{createTableSql}}\");");
        sb.AppendLine($"            await DB.CreateTable(\"{Esc(tableName)}\", createTableSql);");
        sb.AppendLine($"            Logger.Info(tenantId, userId, \"[{className}DAL.CreateTableIfNotExists] 主表创建成功: {tableName}\");");
        sb.AppendLine();

        // Log table
        sb.AppendLine("            // === 日志表 ===");
        sb.AppendLine("            if (createLogTable)");
        sb.AppendLine("            {");
        EmitCreateLogTableSql(sb, model, "                ");
        sb.AppendLine("            }");
        sb.AppendLine();

        // Audit table
        if (model.NeedAuditTable)
        {
            sb.AppendLine("            // === 审计表 ===");
            EmitCreateAuditTableAndTrigger(sb, model);
        }

        sb.AppendLine($"            Logger.Info(tenantId, userId, \"[{className}DAL.CreateTableIfNotExists] 创建完成: {tableName}\");");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
    }

    private static void EmitCreateTableSqlString(StringBuilder sb, EntityModel model)
    {
        sb.AppendLine("            var createTableSql =");
        sb.Append($"                \"CREATE TABLE IF NOT EXISTS \\\"{model.TableName}\\\" (\" +");
        sb.AppendLine();

        for (int i = 0; i < model.Columns.Count; i++)
        {
            var col = model.Columns[i];
            var suffix = "";
            if (col.IsPrimaryKey)
                suffix = " PRIMARY KEY";
            else if (col.IsRequired || !col.IsNullable)
                suffix = " NOT NULL";

            var sep = i < model.Columns.Count - 1 ? ", " : "";
            sb.AppendLine($"                \"\\\"{col.ColumnName}\\\" {col.PgType}{suffix}{sep}\" +");
        }

        if (model.IsTenantTable)
            sb.AppendLine("                \") PARTITION BY LIST (tenant_id);\";");
        else
            sb.AppendLine("                \");\";");
    }

    private static void EmitCreateLogTableSql(StringBuilder sb, EntityModel model, string indent)
    {
        var tableName = model.TableName;
        var logTable = tableName + "_log";
        var className = model.ClassName;

        sb.AppendLine($"{indent}var createLogTableSql =");
        sb.AppendLine($"{indent}    \"CREATE TABLE IF NOT EXISTS \\\"{logTable}\\\" (\" +");
        sb.AppendLine($"{indent}    \"logid BIGSERIAL PRIMARY KEY, \" +");
        sb.AppendLine($"{indent}    \"id BIGINT NOT NULL, \" +");
        sb.AppendLine($"{indent}    \"opt CHAR(1) NOT NULL\" +");
        sb.AppendLine($"{indent}    \");\";");
        sb.AppendLine();
        sb.AppendLine($"{indent}Logger.Info(tenantId, userId, $\"[{className}DAL.CreateTableIfNotExists] 日志表SQL: {{createLogTableSql}}\");");
        sb.AppendLine($"{indent}await DB.CreateTable(\"{Esc(logTable)}\", createLogTableSql);");
        sb.AppendLine($"{indent}Logger.Info(tenantId, userId, \"[{className}DAL.CreateTableIfNotExists] 日志表创建成功: {logTable}\");");
        sb.AppendLine();

        // Log trigger (standalone, only when no audit table or audit table handles it separately)
        if (!model.NeedAuditTable)
        {
            EmitLogTriggerSql(sb, model, indent);
        }
    }

    private static void EmitLogTriggerSql(StringBuilder sb, EntityModel model, string indent)
    {
        var tableName = model.TableName;
        var logTable = tableName + "_log";
        var triggerFunc = tableName + "_log_trigger_func";
        var trigger = tableName + "_log_trigger";
        var className = model.ClassName;

        sb.AppendLine($"{indent}var createLogTriggerFuncSql =");
        sb.AppendLine($"{indent}    \"CREATE OR REPLACE FUNCTION \\\"{triggerFunc}\\\"() \" +");
        sb.AppendLine($"{indent}    \"RETURNS TRIGGER AS $$ \" +");
        sb.AppendLine($"{indent}    \"BEGIN \" +");
        sb.AppendLine($"{indent}    \"IF TG_OP = 'INSERT' THEN \" +");
        sb.AppendLine($"{indent}    \"INSERT INTO \\\"{logTable}\\\" (id, opt) VALUES (NEW.id, 'I'); RETURN NEW; \" +");
        sb.AppendLine($"{indent}    \"ELSIF TG_OP = 'UPDATE' THEN \" +");
        sb.AppendLine($"{indent}    \"INSERT INTO \\\"{logTable}\\\" (id, opt) VALUES (NEW.id, 'U'); RETURN NEW; \" +");
        sb.AppendLine($"{indent}    \"ELSIF TG_OP = 'DELETE' THEN \" +");
        sb.AppendLine($"{indent}    \"INSERT INTO \\\"{logTable}\\\" (id, opt) VALUES (OLD.id, 'D'); RETURN OLD; \" +");
        sb.AppendLine($"{indent}    \"END IF; RETURN NULL; \" +");
        sb.AppendLine($"{indent}    \"END; $$ LANGUAGE plpgsql;\";");
        sb.AppendLine();
        sb.AppendLine($"{indent}var conn1 = DB.GetConnection();");
        sb.AppendLine($"{indent}try");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    using var cmd1 = new NpgsqlCommand(createLogTriggerFuncSql, conn1);");
        sb.AppendLine($"{indent}    await cmd1.ExecuteNonQueryAsync();");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine($"{indent}finally {{ DB.ReturnConnection(conn1); }}");
        sb.AppendLine();

        sb.AppendLine($"{indent}var createLogTriggerSql =");
        sb.AppendLine($"{indent}    \"CREATE TRIGGER \\\"{trigger}\\\" \" +");
        sb.AppendLine($"{indent}    \"AFTER INSERT OR UPDATE OR DELETE ON \\\"{tableName}\\\" \" +");
        sb.AppendLine($"{indent}    \"FOR EACH ROW EXECUTE FUNCTION \\\"{triggerFunc}\\\"();\";");
        sb.AppendLine();
        sb.AppendLine($"{indent}var conn2 = DB.GetConnection();");
        sb.AppendLine($"{indent}try");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    using var cmd2 = new NpgsqlCommand(createLogTriggerSql, conn2);");
        sb.AppendLine($"{indent}    await cmd2.ExecuteNonQueryAsync();");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine($"{indent}finally {{ DB.ReturnConnection(conn2); }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}Logger.Info(tenantId, userId, \"[{className}DAL.CreateTableIfNotExists] 日志触发器创建成功: {trigger}\");");
    }

    private static void EmitCreateAuditTableAndTrigger(StringBuilder sb, EntityModel model)
    {
        var tableName = model.TableName;
        var auditTable = tableName + "_audit";
        var className = model.ClassName;
        var indent = "            ";

        // Audit table DDL
        sb.AppendLine($"{indent}var createAuditTableSql =");
        sb.AppendLine($"{indent}    \"CREATE TABLE IF NOT EXISTS \\\"{auditTable}\\\" (\" +");
        sb.AppendLine($"{indent}    \"audit_id BIGSERIAL PRIMARY KEY, \" +");
        sb.AppendLine($"{indent}    \"id BIGINT NOT NULL, \" +");
        sb.AppendLine($"{indent}    \"opt CHAR(1) NOT NULL, \" +");
        sb.AppendLine($"{indent}    \"operated_at TIMESTAMPTZ NOT NULL DEFAULT now(), \" +");
        sb.AppendLine($"{indent}    \"operator_id BIGINT NOT NULL, \" +");
        if (model.IsTenantTable)
        {
            sb.AppendLine($"{indent}    \"tenant_id INT NOT NULL, \" +");
        }
        sb.AppendLine($"{indent}    \"snapshot JSONB NOT NULL\" +");
        if (model.IsTenantTable)
            sb.AppendLine($"{indent}    \") PARTITION BY LIST (tenant_id);\";");
        else
            sb.AppendLine($"{indent}    \");\";");
        sb.AppendLine();
        sb.AppendLine($"{indent}Logger.Info(tenantId, userId, $\"[{className}DAL.CreateTableIfNotExists] 审计表SQL: {{createAuditTableSql}}\");");
        sb.AppendLine($"{indent}await DB.CreateTable(\"{Esc(auditTable)}\", createAuditTableSql);");
        sb.AppendLine($"{indent}Logger.Info(tenantId, userId, \"[{className}DAL.CreateTableIfNotExists] 审计表创建成功: {auditTable}\");");
        sb.AppendLine();

        // Index on audit table for main table id
        sb.AppendLine($"{indent}// 审计表主表id索引");
        sb.AppendLine($"{indent}await DB.CreateIndex(\"idx_{auditTable}_id\", \"{Esc(auditTable)}\", \"id\", false);");
        sb.AppendLine();

        // Audit trigger function (merged with log table writes when createLogTable is true)
        var triggerFunc = tableName + "_audit_trigger_func";
        var trigger = tableName + "_audit_trigger";
        var logTable = tableName + "_log";

        var tenantInsertCols = model.IsTenantTable ? ", tenant_id" : "";
        var tenantNewVals = model.IsTenantTable ? ", NEW.tenant_id" : "";
        var tenantOldVals = model.IsTenantTable ? ", OLD.tenant_id" : "";

        sb.AppendLine($"{indent}var createAuditTriggerFuncSql =");
        sb.AppendLine($"{indent}    \"CREATE OR REPLACE FUNCTION \\\"{triggerFunc}\\\"() \" +");
        sb.AppendLine($"{indent}    \"RETURNS TRIGGER AS $$ \" +");
        sb.AppendLine($"{indent}    \"DECLARE v_operator_id BIGINT; \" +");
        sb.AppendLine($"{indent}    \"BEGIN \" +");
        sb.AppendLine($"{indent}    \"v_operator_id := COALESCE(current_setting('app.user_id', true)::BIGINT, 0); \" +");
        sb.AppendLine($"{indent}    \"IF TG_OP = 'INSERT' THEN \" +");
        sb.AppendLine($"{indent}    \"INSERT INTO \\\"{auditTable}\\\" (id, opt, operator_id{tenantInsertCols}, snapshot) \" +");
        sb.AppendLine($"{indent}    \"VALUES (NEW.id, 'I', v_operator_id{tenantNewVals}, to_jsonb(NEW)); \" +");
        sb.AppendLine($"{indent}    \"RETURN NEW; \" +");
        sb.AppendLine($"{indent}    \"ELSIF TG_OP = 'UPDATE' THEN \" +");
        sb.AppendLine($"{indent}    \"INSERT INTO \\\"{auditTable}\\\" (id, opt, operator_id{tenantInsertCols}, snapshot) \" +");
        sb.AppendLine($"{indent}    \"VALUES (NEW.id, 'U', v_operator_id{tenantNewVals}, to_jsonb(OLD)); \" +");
        sb.AppendLine($"{indent}    \"RETURN NEW; \" +");
        sb.AppendLine($"{indent}    \"ELSIF TG_OP = 'DELETE' THEN \" +");
        sb.AppendLine($"{indent}    \"INSERT INTO \\\"{auditTable}\\\" (id, opt, operator_id{tenantInsertCols}, snapshot) \" +");
        sb.AppendLine($"{indent}    \"VALUES (OLD.id, 'D', v_operator_id{tenantOldVals}, to_jsonb(OLD)); \" +");
        sb.AppendLine($"{indent}    \"RETURN OLD; \" +");
        sb.AppendLine($"{indent}    \"END IF; RETURN NULL; \" +");
        sb.AppendLine($"{indent}    \"END; $$ LANGUAGE plpgsql;\";");
        sb.AppendLine();
        sb.AppendLine($"{indent}var connA = DB.GetConnection();");
        sb.AppendLine($"{indent}try");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    using var cmdA = new NpgsqlCommand(createAuditTriggerFuncSql, connA);");
        sb.AppendLine($"{indent}    await cmdA.ExecuteNonQueryAsync();");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine($"{indent}finally {{ DB.ReturnConnection(connA); }}");
        sb.AppendLine();

        sb.AppendLine($"{indent}var createAuditTriggerSql =");
        sb.AppendLine($"{indent}    \"CREATE TRIGGER \\\"{trigger}\\\" \" +");
        sb.AppendLine($"{indent}    \"AFTER INSERT OR UPDATE OR DELETE ON \\\"{tableName}\\\" \" +");
        sb.AppendLine($"{indent}    \"FOR EACH ROW EXECUTE FUNCTION \\\"{triggerFunc}\\\"();\";");
        sb.AppendLine();
        sb.AppendLine($"{indent}var connB = DB.GetConnection();");
        sb.AppendLine($"{indent}try");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    using var cmdB = new NpgsqlCommand(createAuditTriggerSql, connB);");
        sb.AppendLine($"{indent}    await cmdB.ExecuteNonQueryAsync();");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine($"{indent}finally {{ DB.ReturnConnection(connB); }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}Logger.Info(tenantId, userId, \"[{className}DAL.CreateTableIfNotExists] 审计触发器创建成功: {trigger}\");");
        sb.AppendLine();
    }

    private static void EmitEnsureColumnLength(StringBuilder sb, EntityModel model)
    {
        var tableName = model.TableName;
        var className = model.ClassName;

        sb.AppendLine($"        /// <summary>检查并扩展 {className} 表字段长度</summary>");
        sb.AppendLine("        public static async ValueTask<bool> EnsureColumnLength(int tenantId, long userId)");
        sb.AppendLine("        {");

        if (!string.IsNullOrEmpty(model.ViewSql))
        {
            sb.AppendLine($"            Logger.Info(tenantId, userId, \"[{className}DAL.EnsureColumnLength] 视图不支持字段扩展\");");
            sb.AppendLine("            return false;");
            sb.AppendLine("        }");
            return;
        }

        sb.AppendLine($"            Logger.Info(tenantId, userId, \"[{className}DAL.EnsureColumnLength] 开始检查字段, 表名={tableName}\");");
        sb.AppendLine();
        sb.AppendLine($"            var (result, fields) = await DB.GetFieldsInfor(\"{Esc(tableName)}\", reader => new DbField");
        sb.AppendLine("            {");
        sb.AppendLine("                FieldName = reader.GetString(0),");
        sb.AppendLine("                DataType = reader.GetString(1),");
        sb.AppendLine("                MaxLength = reader.IsDBNull(2) ? null : reader.GetInt32(2),");
        sb.AppendLine("                NumericPrecision = reader.IsDBNull(3) ? null : reader.GetInt32(3),");
        sb.AppendLine("                NumericScale = reader.IsDBNull(4) ? null : reader.GetInt32(4),");
        sb.AppendLine("                IsNullable = reader.GetString(5) == \"YES\",");
        sb.AppendLine("                IsPrimaryKey = reader.GetBoolean(6)");
        sb.AppendLine("            });");
        sb.AppendLine();
        sb.AppendLine("            if (fields == null) return false;");
        sb.AppendLine("            var changed = false;");
        sb.AppendLine();

        // Check varchar / decimal columns that have Length specified
        for (int i = 0; i < model.Columns.Count; i++)
        {
            var col = model.Columns[i];
            if (col.Length <= 0) continue;

            sb.AppendLine($"            // 检查字段: {col.ColumnName}");
            sb.AppendLine("            {");
            sb.AppendLine("                DbField? existing = null;");
            sb.AppendLine($"                for (int i = 0; i < fields.Count; i++)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    if (fields[i].FieldName == \"{col.ColumnName}\")");
            sb.AppendLine("                    {");
            sb.AppendLine("                        existing = fields[i];");
            sb.AppendLine("                        break;");
            sb.AppendLine("                    }");
            sb.AppendLine("                }");
            sb.AppendLine("                if (existing != null)");
            sb.AppendLine("                {");

            if (col.ClrTypeName == "string" && col.Length > 0)
            {
                sb.AppendLine($"                    if (existing.MaxLength.HasValue && existing.MaxLength.Value < {col.Length})");
                sb.AppendLine("                    {");
                sb.AppendLine($"                        Logger.Info(tenantId, userId,");
                sb.AppendLine($"                            $\"[{className}DAL.EnsureColumnLength] 扩展字段 {col.ColumnName}: {{existing.MaxLength}} -> {col.Length}\");");
                sb.AppendLine($"                        await DB.AlterTable(\"{Esc(tableName)}\", \"{col.ColumnName}\",");
                sb.AppendLine($"                            \"varchar\", \"{col.Length}\", \"\", {(col.IsNullable ? "true" : "false")}, {(col.IsPrimaryKey ? "true" : "false")});");
                sb.AppendLine("                        changed = true;");
                sb.AppendLine("                    }");
            }
            else if (col.ClrTypeName == "decimal")
            {
                var len = col.Length > 0 ? col.Length : 12;
                sb.AppendLine($"                    if (existing.NumericPrecision.HasValue && existing.NumericPrecision.Value < {len})");
                sb.AppendLine("                    {");
                sb.AppendLine($"                        Logger.Info(tenantId, userId,");
                sb.AppendLine($"                            $\"[{className}DAL.EnsureColumnLength] 扩展字段 {col.ColumnName}: precision={{existing.NumericPrecision}} -> {len}\");");
                sb.AppendLine($"                        await DB.AlterTable(\"{Esc(tableName)}\", \"{col.ColumnName}\",");
                sb.AppendLine($"                            \"decimal\", \"{len}\", \"{col.Precision}\", {(col.IsNullable ? "true" : "false")}, {(col.IsPrimaryKey ? "true" : "false")});");
                sb.AppendLine("                        changed = true;");
                sb.AppendLine("                    }");
            }

            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine();
        }

        sb.AppendLine("            return changed;");
        sb.AppendLine("        }");
    }

    private static void EmitCreateIndexIfNotExists(StringBuilder sb, EntityModel model)
    {
        var tableName = model.TableName;
        var className = model.ClassName;

        sb.AppendLine($"        /// <summary>创建 {className} 表索引</summary>");
        sb.AppendLine("        public static async ValueTask<bool> CreateIndexIfNotExists(int tenantId, long userId)");
        sb.AppendLine("        {");

        if (!string.IsNullOrEmpty(model.ViewSql))
        {
            sb.AppendLine($"            Logger.Info(tenantId, userId, \"[{className}DAL.CreateIndexIfNotExists] 视图不支持索引\");");
            sb.AppendLine("            return false;");
            sb.AppendLine("        }");
            return;
        }

        sb.AppendLine($"            Logger.Info(tenantId, userId, \"[{className}DAL.CreateIndexIfNotExists] 开始创建索引, 表名={tableName}\");");
        sb.AppendLine("            var created = false;");
        sb.AppendLine();

        for (int i = 0; i < model.Indexes.Count; i++)
        {
            var idx = model.Indexes[i];
            var unique = idx.IsUnique ? "true" : "false";
            var columns = string.Join(", ", idx.Columns);

            sb.AppendLine($"            // 索引: {idx.IndexName}");
            sb.AppendLine($"            var r{i} = await DB.CreateIndex(\"{Esc(idx.IndexName)}\", \"{Esc(tableName)}\", \"{Esc(columns)}\", {unique});");
            sb.AppendLine($"            if (r{i} == DDLStatus.Success)");
            sb.AppendLine("            {");
            sb.AppendLine($"                Logger.Info(tenantId, userId, \"[{className}DAL.CreateIndexIfNotExists] 索引创建成功: {idx.IndexName}\");");
            sb.AppendLine("                created = true;");
            sb.AppendLine("            }");
            sb.AppendLine($"            else if (r{i} == DDLStatus.Existed)");
            sb.AppendLine("            {");
            sb.AppendLine($"                Logger.Info(tenantId, userId, \"[{className}DAL.CreateIndexIfNotExists] 索引已存在, 跳过: {idx.IndexName}\");");
            sb.AppendLine("            }");
            sb.AppendLine();
        }

        sb.AppendLine("            return created;");
        sb.AppendLine("        }");
    }

    private static string Esc(string s)
    {
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
