using System.Text;
using YTStdEntity.Generator.Models;

namespace YTStdEntity.Generator.Emitters;

/// <summary>描述类代码生成器：生成字段常量/元数据/索引器代码</summary>
internal static class DescEmitter
{
    /// <summary>生成 {Entity}Desc.g.cs 内容</summary>
    public static string Emit(EntityModel model)
    {
        var sb = new StringBuilder(2048);
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using YTStdEntity;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static partial class {model.ClassName}Desc");
        sb.AppendLine("    {");

        // Name const
        sb.AppendLine($"        public const string Name = \"{model.TableName}\";");
        sb.AppendLine();

        // IsTenant const
        sb.AppendLine($"        public const bool IsTenant = {(model.IsTenantTable ? "true" : "false")};");
        sb.AppendLine();

        // Fields nested class
        EmitFieldsClass(sb, model);
        sb.AppendLine();

        // DictFieldMetas
        EmitDictFieldMetas(sb, model);
        sb.AppendLine();

        // GetFieldMeta method
        EmitGetFieldMeta(sb, model);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitFieldsClass(StringBuilder sb, EntityModel model)
    {
        sb.AppendLine("        public static class Fields");
        sb.AppendLine("        {");
        foreach (var col in model.Columns)
        {
            sb.AppendLine($"            public const string {col.PropertyName} = \"{col.ColumnName}\";");
        }
        sb.AppendLine("        }");
    }

    private static void EmitDictFieldMetas(StringBuilder sb, EntityModel model)
    {
        sb.AppendLine("        private static readonly Dictionary<string, YTFieldMeta> _fieldMetas = new Dictionary<string, YTFieldMeta>");
        sb.AppendLine("        {");

        for (int i = 0; i < model.Columns.Count; i++)
        {
            var col = model.Columns[i];
            var comma = i < model.Columns.Count - 1 ? "," : "";
            sb.AppendLine($"            {{ \"{col.ColumnName}\", new YTFieldMeta");
            sb.AppendLine("            {");
            sb.AppendLine($"                Name = \"{col.ColumnName}\",");
            sb.AppendLine($"                Type = \"{col.PgType}\",");
            sb.AppendLine($"                Length = {col.Length},");
            sb.AppendLine($"                Precision = {col.Precision},");
            sb.AppendLine($"                IsNullable = {(col.IsNullable ? "true" : "false")},");
            sb.AppendLine($"                IsPrimaryKey = {(col.IsPrimaryKey ? "true" : "false")},");
            sb.AppendLine($"                IsTenant = {(col.IsTenantField ? "true" : "false")},");
            sb.AppendLine($"            }} }}{comma}");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        public static IReadOnlyDictionary<string, YTFieldMeta> DictFieldMetas => _fieldMetas;");
    }

    private static void EmitGetFieldMeta(StringBuilder sb, EntityModel model)
    {
        sb.AppendLine("        public static YTFieldMeta? GetFieldMeta(string fieldName)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_fieldMetas.TryGetValue(fieldName, out var meta))");
        sb.AppendLine("                return meta;");
        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
    }
}
